### PR TITLE
PHSEN startup config updates

### PR DESCRIPTION
**Pull request by kehunt06**
Adding comments to the startup config files to capture the default configs for reference.

### CODE REVIEW

**Comment by danmergens** [comment]
if you pulled the config from the instrument, go ahead and set the one value that differs as set in the config and we will change if the MIO decides it needs to be updated.

**Comment by kehunt06** [comment]
My concern is that it's not just one param. It's all of them. Every single "startup" param for this instrument, that is listed in the startup config, has a value of zero in the default configs. That just doesn't seem correct to me, but maybe it is. The other five instruments all match the startup configs as they are.

**Comment by kehunt06** [comment]
Is it desired to have all of these changed to zero?

**Comment by manalang** [comment]
Kirk,

Which specific instrument is this? 

Dana

**Comment by kehunt06** [comment]
CE02SHBP-LJ01D-10-PHSEND103

If you look at the comments I've added at the bottom of the YAML file for this instrument, you can see what the values are currently on the instrument, and that the instrument params (NOT the driver params/commands, such as auto_sample_interval) all have a value of zero.

**Comment by danmergens** [comment]
Since this is just adding information (not changing any parameters) I'm going to merge this. If we decide later that the value needs to change for the one instrument we can update (although it appears to be a mistake in the deployed config).

**Comment by manalang** [comment]
I just sent the "L" command to this instrument. It looks like it has plenty of non-zero config parameters. 

Dana

**Comment by kehunt06** [comment]
Here's the data particle output from your L command. Note all the zero
values. Perhaps something is going wrong when breaking it up into a data
particle?

The port_timestamp for the following is: 2016-06-15T20:10:29.218218

"pump_on_ind": 0,
"send_record_type": 0,
"number_reagent_pumps": 0,
"pv_off_ind": 0,
"number_samples_averaged": 0,
"send_live_records": 0,
"pump_on_flush": 0,
"slot2_independent_schedule": 0,
"extend_global_config": 0,
"driver_timestamp": 3675010229.4459119,
"slot1_independent_schedule": 0,
"slot1_follows_sami_sample": 0,
"salinity_delay": 0,
"valve_delay": 0,
"pmi_sample_schedule": 1,
"number_flushes": 0,
"start_time_offset": 1114112,
"driver_id_device1": 8,
"driver_id_device2": 0,
"driver_id_device3": 0,
"sami_sample_schedule": 0,
"number_blanks": 0,
"recording_time": 4359,
"internal_timestamp": 0.0,
"pump_off_to_measure": 0,
"pk": {
  "node": "LJ01D",
  "stream": "phsen_configuration",
  "subsite": "CE02SHBP",
  "deployment": 2,
  "time": 3675010229.2182178,
  "sensor": "10-PHSEND103",
  "method": "streamed"
},
"slot2_follows_sami_sample": 0,
"driver_id_prestart": 0,
"pump_measure_t": 0,
"parameter_pointer_sami": 8,
"parameter_pointer_prestart": 0,
"ingestion_timestamp": 3675010230.204,
"port_timestamp": 3675010229.2182178,
"time": 3675010229.2182178,
"driver_id_sami": 1,
"pump_off_flush": 0,
"slot3_independent_schedule": 0,
"timer_interval_sami": 3605536,
"timer_interval_device1": 528388,
"timer_interval_device2": 530176,
"timer_interval_device3": 0,
"preferred_timestamp": "port_timestamp",
"parameter_pointer_device1": 16,
"measure_to_pump_on": 0,
"parameter_pointer_device3": 0,
"parameter_pointer_device2": 0,
"launch_time": 285212672,
"number_measurements": 0,
"slot3_follows_sami_sample": 0,
"use_baud_rate_57600": 0,
"timer_interval_prestart": 0

**Comment by manalang** [comment]
I just sent the "L" command to PHSENB106 on PC01B. The response looks very similar to the PHSEND103 response. Can you compare that? Looks like the zeros are in all the same places.

Dana

**Comment by kehunt06** [comment]
Here's a data particle comparison spreadsheet

https://drive.google.com/open?id=1UmrUZC2ulczxj1EUWsZXi2rlnCM12iQC_3IkBol67r0

**Comment by kehunt06** [comment]
On the spreadsheet, from the previous comment, I highlighted the startup Params in green.

**Pull request merged**
